server:
  # 端口
  port: 9090
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gradle?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: qwer1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# 循环依赖注入
#  main:
#    allow-circular-references: true
  redis:
    timeout: 10000
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞等待时间
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

# Mybatis-plus配置
mybatis-plus:
#  #配置Mapper映射文件
#  mapper-locations: classpath*:/mapper/*Mapper.xml
#  # 配置MyBatis数据返回类型别名（默认别名是类名）
#  type-aliases-package: cn.ut.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800 #（7天）
#  expiration: 60 #（7天）
  # JWT 负载中拿到开头
  tokenHead: Bearer