server:
  # 端口
  port: 9090
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gradle?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: qwer1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true
# Mybatis-plus配置
mybatis-plus:
#  #配置Mapper映射文件
#  mapper-locations: classpath*:/mapper/*Mapper.xml
#  # 配置MyBatis数据返回类型别名（默认别名是类名）
#  type-aliases-package: cn.ut.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer